### ISSUE TITLE
Проработать поиск пары для пользователя

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/RandomCoffeeBotTelegram#115]
# Why?

Сейчас у нас стоит заглушка "Ищу тебе пару! Как только найду, обязательно сообщу!" в хендлере **go**. 
А нам нужно отправлять это сообщение, если пользователя для пары не нашлось в данным момент.
Соответсвенно начинаем реализовывать хендлеры и функции для подбора пары). 
Посмотреть алгоритм можно в документации https://github.com/Studio-Yandex-Practicum/RandomCoffeeBotTelegram/blob/develop/docs/flowchart_search_pair.jpg

# How To Do?

Для начала, чтобы не было путаницы можно сразу поправить диаграмму состояний. Как оказалось там есть лишний шаг, ненужный нам.
![2023-10-16_16-00](https://github.com/Studio-Yandex-Practicum/RandomCoffeeBotTelegram/assets/69113745/d536f45b-2821-432e-be43-ecb45875aefa)

Создаём необхоимые хендлеры а обработку желательно проводить в отдельных функциях
src/bot/utils/pair.py - это заготовка, ее можно поменять если необходимо.

Сейчас у нас есть в Makefile команды для создания пользователей. Это больше для мануального тестирования и удобства.

# Where?

src/bot

**Comment by KonstantinRaikhert** [comment]
@Andrianova-T Приоритет задачи меняется)) Может тебе кого нибудь в помощь? @D4rkLght или @Ezereul

**Comment by Andrianova-T** [comment]
Постараюсь сегодня сделать
