### ISSUE TITLE
Разобраться и пофиксить проблемы с добавлением новых профессий через админку.

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/RandomCoffeeBotTelegram#117]
# Why?

Суть такая:
На шаге, где студенту предлагается выбрать профессию отображаются 4 которые добавлены через миграции.
И все они нажимаются и выбираются. НО!!! Если добавить новую профессию через админ панель, то она будет отображаться, но станет не кликабельной. Для того, чтобы она стала кликабельной - нужно перезагрузить приложение.
Скорее всего проблема в инициализации бота через приложение джанги.

# How To Do?

1. Найти причину, почему необхоимо перезагружать приложение, ну и соотвественно постараться пофиксить. 
P.S. Может я не прав и решается намного проще.
2. Сразу в готовых миграциях поправить и добавить с преффиксом profession ключи в обьектах. Сейчас они создаются без ключей.

# Where?

src/bot

**Comment by KonstantinRaikhert** [comment]
@D4rkLght Вот такую штуку интересную обнаружил) Возможно все дело в иницализации через приложение джанги. Нужно отдебажить..

**Comment by Ezereul** [comment]
@KonstantinRaikhert @D4rkLght У меня есть предположение на этот счет: хендер для кнопки с профессией создается в момент инициализации бота.
```
States.PROFESSION_CHOICE: [
                CallbackQueryHandler(
                    continue_name, pattern=CONTINUE_NAME_PATTERN
                )
            ]
            + [
                CallbackQueryHandler(
                    profession_choice,
                    pattern=await create_pattern_profession_choice(),
                ),
            ],
```
Здесь создаются паттерны для колбеков, на которые будет реагировать хендлер. Эта функция отрабатывает только при инициализации, поэтому если во время работы добавить профессию, то реакции на новую callback_data не будет. А кнопка отображается, потому что в самом хенделере функция для создания клавиатуры `build_profession_keyboard` отрабатывает при каждом вызове
