### ISSUE TITLE
Настройка стейджа для Dev, настройка VPS

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/RandomCoffeeBotTelegram#124]
# Why?

Нужно развернуть наше приложение на сервере, должнен быть активен Redis, Postgres, само приложение.

# How To Do?

Одна из особенностей, что нужно будет добавить NGINX для раздачи админки по доменному имени. Дам пока своё.
Сейчас нужно:
1. Настроить VPS - сделать отдельного пользователя для деплоя, сделать безопасным доступ, разворачивать контейнер с гитхаба.
2. Составить список необходимых секретов для environments, позже добавим.
3. Написать workflow action для разворачивание develop ветки

Написать мне свой ssh key и я предоставлю доступ к серверу.

# Where?

51.250.86.87

**Comment by KonstantinRaikhert** [comment]
@Ezereul Полёт фантазии девопсера, берёшь?)

**Comment by Ezereul** [comment]
@KonstantinRaikhert Конечно)
