### ISSUE TITLE
Реализовать завершающие стейты интервью

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/RandomCoffeeBotTelegram#138]
# Why?

После того, как пришло сообщение: "Удалось ли созвониться?", необходимо отправлять на шаг, где мы переводим пару в завершенные.

# How To Do?

![2023-10-24_13-19](https://github.com/Studio-Yandex-Practicum/RandomCoffeeBotTelegram/assets/69113745/afe3bfb4-e219-48f7-859d-5824de8ea61b)
- для студента и рекрутера отдельные сообщения.
- не забыть про метод delete_pair
- кнопка GO должна возвращать на поиск новой пары (без повторной регистрации)
- кнопка "в следующий раз" возвращает нас на next_time

# Where?

src/bot/handlers

**Comment by KonstantinRaikhert** [comment]
@Andrianova-T Так как ты уже реализовала метод и свободна) Если не справляешься, то маякни будем подключать помощь)

**Comment by Andrianova-T** [comment]
@KonstantinRaikhert Я столкнулась с проблемой, пока не нашла решения: кнопка "Да" после вопроса о созвоне срабатывает только у того, кто запустил поиск пары последним. Закоммитила пока как есть, завтра попробую на свежую голову разобраться, в чем дело.
