### ISSUE TITLE
Дописать недостающие юнит тесты на хендлеры и клавиатуры

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/RandomCoffeeBotTelegram#151]
# Why?

Сейчас мы имеет приложение, которое пойдёт в первый релиз скажем так)) Нужно дописать юниттесты, чтобы потом было не так больно, если будем что то менять.

# How To Do?

Пройтись по хендлерам и клавиатурам. Написать необходимые тесты.
Руководствоваться можно уже написанными тестами. Можно еще посмотреть примеры в официальном репозитории фреймворка: https://github.com/python-telegram-bot/python-telegram-bot/blob/master/tests/README.rst В папке tests много примеров

# Where?
У нас тесты лежат в src/tests

**Comment by KonstantinRaikhert** [comment]
@Romanroman99 @teehazee Думаю лучше эту таску вам разделить на двоих.

**Comment by teehazee** [comment]
Константин, вопрос по таске:
поизучали код, уже написанные тесты
не до конца понятно какой функционал тестами ещё не покрыт (большинство уже написано)

по хэндлерам нет тестов на поиск пары (search_pair) и на найденную пару (found_pair)

**Comment by teehazee** [comment]
А по клавиатуре не хватает теста для build_profession_keyboard. 

Ещё обратил внимание на блок ридми «Написание тестов» - там неверно указано расположение фикстур (файла fixture_data.py у нас нет) и расположения основных тестов бота (файл test_bot.py)


![Image](https://github.com/Studio-Yandex-Practicum/RandomCoffeeBotTelegram/assets/113125707/1dfd42b0-b019-4baf-81d7-781860e612f2)

**Comment by KonstantinRaikhert** [comment]
@teehazee Ридми нужно тогда тоже поправить) Хорошо, что обнаружил.
По тестам: сейчас только проводим юнит тестирование, поэтому только хендлеры и клавиатуры. Если больше не обнаружил, реализуй пока эти тесты.

**Comment by teehazee** [comment]
Понял!)

**Comment by teehazee** [comment]
PR оформлен
https://github.com/Studio-Yandex-Practicum/RandomCoffeeBotTelegram/pull/174

апдейт по ранее заявленному тесту на клавиатуру (build_profession_keyboard):
данный тест в наличии, плохо искали, клава тестируется в тесте хэндлера test_continue_name.py

по тестам на данный момент получается всё)

**Comment by teehazee** [comment]
кстати забыл отредактировать ридми в тест-блоке
@KonstantinRaikhert можно тогда отдельной таской?)

**Comment by KonstantinRaikhert** [comment]
@teehazee извиняюсь не заметил вовремя. Тогда таску сейчас за тобой закреплю
