### ISSUE TITLE
Устранить возможность создать рекрутера и студента с одинаковыми ID

### ISSUE THREAD

**Issue by Andrianova-T** [Studio-Yandex-Practicum/RandomCoffeeBotTelegram#152]
# Why?

Сейчас есть возможность создать рекрутера и студента с одинаковыми ID через админ панель

# How To Do?

# Where?

**Comment by KonstantinRaikhert** [comment]
@Andrianova-T Вроде ты еще о чём то говорила на созвоне?) Не нашёл вторую таску.
