### ISSUE TITLE
Поправить орфографические, логические ошибки в сообщениях бота.

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/RandomCoffeeBotTelegram#157]
# Why?

Нужно поправить орфографию в сообщениях и по возможности пробежаться по всему проекту (админка). Исправить, где необходимо)
![ff46e664-98c4-447d-b684-0491e050a76d](https://github.com/Studio-Yandex-Practicum/RandomCoffeeBotTelegram/assets/69113745/15225e46-69ac-4314-b586-86f4d96fd686)

**Comment by Andrianova-T** [comment]
@KonstantinRaikhert в сообщениях бота обращаемся к пользователю то на Вы, то на ты. Какое обращение стоит оставить?

**Comment by KonstantinRaikhert** [comment]
Яндекс практикум рекомендует общение на ты, но в уважительной форме😅 Поэтому думаю стоит везде перейти на "ты".
