### ISSUE TITLE
Поменять url админки на корневой url

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/RandomCoffeeBotTelegram#168]
# Why?

Сейчас у нас например на стейдже адрес админки jetrai.ru/admin. А нужно - jetrai.ru
То есть по хорошему обращаться к корневому пути. Так как на домене кроме админки ничего не будет.

# How To Do?

в urls.py меняем пути, тестируем. Главное еще не забыть про nginx!

**Comment by teehazee** [comment]
[fixed]

**Comment by teehazee** [comment]
[fixed]

**Comment by teehazee** [comment]
@KonstantinRaikhert Константин, имею проблемы с запуском стейджа из-за конфликтов имён контейнеров, пока не знаю как решить. Запускаю с целью посмотреть на адрес админки по дефолту и далее чтобы вносить изменения в конфиг nginx и снова проверять.



![Image](https://github.com/Studio-Yandex-Practicum/RandomCoffeeBotTelegram/assets/113125707/1b1c3143-1e80-47e1-8fc2-db581f7f309c)

**Comment by KonstantinRaikhert** [comment]
Попробуй командами остановить все контейнеры. Потом удалить все контейнеры и даже вольюмы. И снова запустить. Бывает у докера иногда такое... Часто встречаюсь на линуксе, что порт занимает, останавливается но порт не освобождает. Хотя у тебя вроде другое.
docker container ls -a Хотя команды думаю сам найдешь)

**Comment by teehazee** [comment]
@KonstantinRaikhert После убивания всего и вся стейдж запущен. Все 4 контейнера на месте.


![Image](https://github.com/Studio-Yandex-Practicum/RandomCoffeeBotTelegram/assets/113125707/44f70f2f-3c20-4c0e-86ea-43d0192ab33c)

**Comment by teehazee** [comment]
Далее в env файле поменял значение POSTGRES_HOST на контейнер с БД (postgres-container-randomcoffee), так как при дефолтных настройках при попытке проверить localhost/admin/ на nginx ловил (скрин)

![Image](https://github.com/Studio-Yandex-Practicum/RandomCoffeeBotTelegram/assets/113125707/5fbf0734-27e3-4bdd-9a31-6d9586d98ff2)

**Comment by teehazee** [comment]
Далее перезапустил стейдж и при той же попытке проверки localhost/admin/ на 80 порту имею вот такое (скрин)

![Image](https://github.com/Studio-Yandex-Practicum/RandomCoffeeBotTelegram/assets/113125707/89d8ac5e-5901-4c57-b1b4-e28a4a7850cf)

пытаюсь найти решение на стаке, но пока безрезультатно

**Comment by KonstantinRaikhert** [comment]
@teehazee Явно проблемы с БД. Во втором скрине ему не нравится, что нет нужной таблицы. Точно ли все миграции применены? А вообще сделай уже пулреквест. Посмотрим

**Comment by teehazee** [comment]
@KonstantinRaikhert PR оформил, буксую на на том же месте, ошибка бд
