### ISSUE TITLE
Добавить визавиг markdown редактор

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/RandomCoffeeBotTelegram#169]
# Why?

Сейчас у нас есть сообщения бота, которые можно редактировать через админ панель. Будет круто, если их можно будет модифицировать различными форматами текста и эмоджи.

# How To Do?

Предлагаю взять вот [этот](https://django-ckeditor.readthedocs.io/en/latest/) редактор.
И можно сделать так же по аналогии с [этим](https://github.com/Studio-Yandex-Practicum/spread_wings_bot/tree/develop) проектом.

# Where?

src/bot/admin.py
src/bot/models.py

**Comment by VladislavYar** [comment]
@KonstantinRaikhert , так-с, редактор добавил (всё взял с другого проекта), поле с фамилией теперь может быть пустым и нашёл где еще используются константы сообщений бота, поменял на вызов корутины.

Есть пару вопросов:
1. Статика для редактора используется сторонняя, на том проекте вся статика в gitignore и нет исключений. Сами ручками загрузим в GitHub или я что-то не понял?
2. Теперь могу удалять файл с константами сообщений бота?

**Comment by KonstantinRaikhert** [comment]
@VladislavYar Блин! Только сейчас увидел твое сообщение.. Видимо нотификация как то криво работает. Просьба пингуй если что в пачке.
i. Да, придётся статику грузить в репозиторий, если конечно нет каких нибудь CDN (хотя не доверяю я им, вдруг сервер упадет их)
ii. Да, можно удалять!)

**Comment by VladislavYar** [comment]
@KonstantinRaikhert , да у меня у самого оповещения живут своей жизнь. Вот оповещение, что на меня повесили эту задачу, пришло только, когда я уже её сделал и задал вопрос вышел :) но думаю эту приколы лично моего телефона.

Хорошо, по ответам понял)
