### ISSUE TITLE
Реализовать защиту для контейнеров от перезагрузки VPS. Создать файл service

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/RandomCoffeeBotTelegram#180]
# Why?

Контейнеры не поднимутся, если произойдет сбой на сервере. Нужно обезопаситься, предлагаю поместить наше приложение в *.service.
[Пример](https://github.com/Studio-Yandex-Practicum/spread_wings_bot/blob/develop/infra/dev/spread_wings_bot.service)

# How To Do?

Создаём в папке infra необходимые скрипты. И желательно сделать так, чтобы сам код с репозитория не копировался на сервер. А копировались необходимые обсуживающие скрипты (compose например). Ну и само приложение обновляется через docker images

# Where?

infra/

**Comment by KonstantinRaikhert** [comment]
@BeerBellyWell тут пачка упала. Не могу отправить сообщения. В общем попробуй пожалуйста. Добавил пользователя в sudo

**Comment by BeerBellyWell** [comment]
@KonstantinRaikhert, просит пароль на любую команду sudo

**Comment by BeerBellyWell** [comment]
![image](https://github.com/Studio-Yandex-Practicum/RandomCoffeeBotTelegram/assets/116052435/d4d7fe50-fce8-4184-a96f-b3fb57d80760)
