### ISSUE TITLE
Сделать миграции с сообщениями бота.

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/RandomCoffeeBotTelegram#183]
# Why?

Необходимо сделать записи в нашей БД через миграции для MessageBot

# How To Do?

Из файла /[src](https://github.com/Studio-Yandex-Practicum/RandomCoffeeBotTelegram/tree/develop/src)/[bot](https://github.com/Studio-Yandex-Practicum/RandomCoffeeBotTelegram/tree/develop/src/bot)/[constants](https://github.com/Studio-Yandex-Practicum/RandomCoffeeBotTelegram/tree/develop/src/bot/constants/messages.py) взять все записи и перенести в БД.
Так же думаю нужно добавить help_text для поля text. Нужно объяснить админу, что {} удалять нельзя.
Ключи к кнопкам придумываем, можно просто на английском языке

# Where?

migrations
Пример миграций /[src](https://github.com/Studio-Yandex-Practicum/RandomCoffeeBotTelegram/tree/develop/src)/[bot](https://github.com/Studio-Yandex-Practicum/RandomCoffeeBotTelegram/tree/develop/src/bot)/[migrations](https://github.com/Studio-Yandex-Practicum/RandomCoffeeBotTelegram/tree/develop/src/bot/migrations/0007_add_formurl_data.py)

**Comment by KonstantinRaikhert** [comment]
@VladislavYar Вот же таска)

**Comment by KonstantinRaikhert** [comment]
@VladislavYar Если есть проблемы с занятостью - может поручим таску другому разработчику? @BeerBellyWell например

**Comment by VladislavYar** [comment]
@KonstantinRaikhert сегодня сделаю, не волнуйтесь)
