### ISSUE TITLE
Реализовать обновление даты входа пользователя в бота по командам /start /help /support

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/RandomCoffeeBotTelegram#196]
# Why?

Сейчас дата входа не обновляется. А понадобится она нам в будущем для удаления пользователей из БД после периода в полгода примерно

# How To Do?

Взять из утилит функцию проверки src/bot/utils/db_utlis/user.py пользователя.
Проверять есть ли пользователь в БД. Если есть - обновить ему дату входа.

# Where?

*Где делаем реализацию задачи, какие сервисы задействованы, ссылка на требования, сcылка на API, скриншоты.*
src/bot/handlers/command_handlers.py

**Comment by BeerBellyWell** [comment]
@KonstantinRaikhert, я правильно понял, что в бд, при командах start, help, и support должна меняться дата в столбце "Заходил в последний раз", оно же last_login_date в моделе?

![Image](https://github.com/Studio-Yandex-Practicum/RandomCoffeeBotTelegram/assets/116052435/083a3639-58d7-4114-9f56-cf2bcc320bc2)

**Comment by KonstantinRaikhert** [comment]
@BeerBellyWell Да. Извини, сразу не заметил вопрос
