### ISSUE TITLE
Привести в порядок админку для Рекрутера и IT специалиста.

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/RandomCoffeeBotTelegram#204]
# Why?

Сейчас у нас если у пользователя нет ника телеграма, сохранятся телефон. Но в админке все равно написано ник телеграма
![2023-11-26_01-51](https://github.com/Studio-Yandex-Practicum/RandomCoffeeBotTelegram/assets/69113745/65b160df-e9f7-4c05-b18e-25a674a83265)
Предлагаю переименовать поле в "Ник телеграма или номер телефона"

# How To Do?

Так же в самой форме привести в порядок поля и отсортировать их по такому принципу:
1. Имя
2. Фамилия
3. telegram ID
4. Ник или телефон
5. Профессия (для IT специалистов)
6. есть пара
7. Дата начала поиска пары

Так же сделать поля ID и ника неизменяемыми

![2023-11-26_01-53](https://github.com/Studio-Yandex-Practicum/RandomCoffeeBotTelegram/assets/69113745/f439e5b4-aac2-46ac-9139-1835bfd3202b)

# Where?

src/bot/admin.py

**Comment by teehazee** [comment]
Вопрос по изменяемости отмеченных полей: на ум приходят только конструкции типа is_editable=False или атрибуты типа readonly. Не совсем понимаю как тут надо действовать.

**Comment by KonstantinRaikhert** [comment]
Лучше readonly думаю в админке.
