### ISSUE TITLE
Реализовать хранение секретов (токен и тд.) в файле env

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/RandomCoffeeBotTelegram#33]
# Why?

Нельзя, чтобы эти данные попадали в репозиторий, поэтому храним в env

# How To Do?

1. Нужно реализовать чтение с env файла в локальной разработке (dotenv?). Читать файл с корня проекта. Добавить туда:
- SECRET_KEY
- DEBUG
- TELEGRAM_TOKEN
- WEBHOOK_MODE
2. Сделать env.example с пояснениями для чего каждый секрет и добавить его в корень проекта.

# Where?
[RandomCoffeeBotTelegram](https://github.com/Studio-Yandex-Practicum/RandomCoffeeBotTelegram)

**Comment by KonstantinRaikhert** [comment]
@Buzhak Есть сложности?

**Comment by Buzhak** [comment]
все ок, работа немного задушила. Кажется все поправил, посмотрел ещё раз, может, что-то и упустил.
