### ISSUE TITLE
Реазизовать модели сущностей для нашего бота

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/RandomCoffeeBotTelegram#35]
# Why?

Уже есть заготовки. Необходимо свериться с ER диаграммой и реализовать их

# How To Do?

в models.py всех приложений прописываем все поля. Заодно сразу все добавляем в первом приближении в админку

# Where?

models.py
admin.py

**Comment by Sobodazh** [comment]
Могу я на себя взять это задание?
