### ISSUE TITLE
Реализация хендлера при нажатии на кнопку "В следующий раз"

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/RandomCoffeeBotTelegram#58]
# Why?

Одно из состояний бота

# How To Do?

![next time](https://github.com/Studio-Yandex-Practicum/RandomCoffeeBotTelegram/assets/69113745/2e412a6c-6ec6-42c8-9b7b-131737bc92eb)

[диаграмма состояний](https://github.com/Studio-Yandex-Practicum/RandomCoffeeBotTelegram/blob/develop/docs/Diagramm%20of%20bot%20logic.jpg)

Важно, чтобы была inline кнопка, которая ссылалась на команду start и возвращала к хендлеру start. Возможно тут уже потребуется вводить состояния бота

# Where?

src/bot/handlers

**Comment by Ezereul** [comment]
Есть готовый код, нужно только косметику навести
