### ISSUE TITLE
Реализовать хендлер знакомства при нажатии на кнопку 'GO'

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/RandomCoffeeBotTelegram#59]
# Why?

Одно из состояний бота

# How To Do?

![introduction](https://github.com/Studio-Yandex-Practicum/RandomCoffeeBotTelegram/assets/69113745/741243f6-4ffa-41a0-b821-40cad2212077)

[диаграмма состояний](https://github.com/Studio-Yandex-Practicum/RandomCoffeeBotTelegram/blob/develop/docs/Diagramm%20of%20bot%20logic.jpg)

Потребуется вводить состояния бота.

# Where?

src/bot/handlers

**Comment by Ezereul** [comment]
Можешь мне скинуть, я уже более менее разобрался, как с ними работать

**Comment by KonstantinRaikhert** [comment]
@Ezereul Лови)

**Comment by KonstantinRaikhert** [comment]
@Ezereul Вообще с кнопкой в следующий раз ты поторопился и оставил без работы @Sobodazh У него таска как раз на эту кнопку)))
