### ISSUE TITLE
Принять решение об использовании инлайн кнопки для выбора "В следующий раз"

### ISSUE THREAD

**Issue by Ezereul** [Studio-Yandex-Practicum/RandomCoffeeBotTelegram#65]
# Why?

Сейчас встал вопрос о том, как правильнее реализовать выбор "В следующий раз". 
Есть два варианта: использовать инлайн кнопку или оставить в сообщении команду /start.
Плюсы для /start:
- Удобно и прозрачно реализуется. При нажатии "В следующий раз" заканчивается диалоговая сессия с пользователем и далее его сообщения будут отлавливать хендлеры команд из entry_points. 
Плюсы инлайн кнопки:
- Все взаимодействие с ботом останется одинаковым, везде будут предсказуемые инлайн кнопки. Под этим подразумевается более дружелюбный для пользователя интерфейс.
Минусы /start:
- Немного меняется интерфейс взаимодействия.  Но команда /start кликабельна в телеграмме, поэтому UX сильно не пострадает (мне кажется так даже лучше)
Минусы инлайн кнопки:
- Нужно создавать еще один обработчик, который далее нужно добавлять либо к глобальным обработчикам бота, либо в entry_points, что кажется не совсем правильным с точки зрения организации кода.

# How To Do?

Определяем, что важнее для нас и пользовательского опыта, отталкиваясь от этого, принимаем решение за использование первого или второго подхода.

# Where?

src/bot

**Comment by Sobodazh** [comment]
я уже сделал по второму варианту с помощью выбора "В следующий раз"
