### ISSUE TITLE
Проработать конструкцию по утверждению имени в боте.

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/RandomCoffeeBotTelegram#78]
# Why?

Если имя задано не верно (не устраивает пользователя), предложение сменить для перехода.

# How To Do?

Определиться, где временно хранить информацию, которую собираем с пользователя и реализуем шаг со сменой имени. Возможно стоит подумать на этим: если имя не задано в телеграме, сразу пропускать этот шаг и спрашивать, "Как вас зовут?"

![2023-09-25_15-55](https://github.com/Studio-Yandex-Practicum/RandomCoffeeBotTelegram/assets/69113745/46253237-e82d-4267-a7e2-d47af4ceb3cf)

# Where?

**Comment by KonstantinRaikhert** [comment]
UPD: кажется мы уже проговаривали, что у юзера в телеге всегда есть имя, верно?

**Comment by Ezereul** [comment]
Да. Возможно вместо имени можно пустой символ вставить, но я не знаю, стоит ли такое ловить.
