### ISSUE TITLE
Создать фабрики и команды в Makefile для генерации тестовых студентов и рекрутеров.

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/RandomCoffeeBotTelegram#84]
# Why?

Для имитации наполнения БД и возможного тестирования, необходимо генерировать пользователей.

# How To Do?

Для генерации есть чудесная библиотека [factory boy](https://factoryboy.readthedocs.io/en/stable/index.html). Она хорошо умеет работать с джангой.
Нам нужно:
- добавить возможность генерации отдельно студента и рекрутера.
- сделать команды в Makefile для отдельной генерации студента, рекрутера так и совместной пары
- можно использовать менеджер команд джанги для удобства.

# Where?

src/bot/factories

**Comment by KonstantinRaikhert** [comment]
@D4rkLght Поможешь Дмитрию?)

**Comment by KonstantinRaikhert** [comment]
Таска приобретает приоритет важности на мой взгляд, для того, чтобы идти дальше и реализовать алгоритм поиска пар

**Comment by D4rkLght** [comment]
@Ku3mi4-51rus Предлагаю работать в ветке feature/factories-student-recruiter, которую я уже сгененировал.

**Comment by Ku3mi4-51rus** [comment]
Прошу прощения за задержку, возникли некоторые трудности с работой именно с файлом Makefile. Ок, свою ветку закрываю, перехожу в вновь созданную)

**Comment by Ku3mi4-51rus** [comment]
сам файл factories.py у меня готов, сейчас пробую сделать консольные команды в make

**Comment by Ku3mi4-51rus** [comment]
с консольными командами, кажется, тоже разобрался) надеюсь к созвону отправлю на проверку. Ярослав очень помог, спасибо))
