### ISSUE TITLE
Подключить Redis для хранения состояний бота

### ISSUE THREAD

**Issue by KonstantinRaikhert** [Studio-Yandex-Practicum/RandomCoffeeBotTelegram#87]
# Why?

Подозреваю, что приложение будет средненагруженным. Поэтому прикрутим редис для хранения состояний. Это нам даст возможность масштабироваться и возможно использовать его для очереди задач (опрашивать пользователей например)

# How To Do?

- Для реализации необходимо заложить возможность использования Redis (какой нибудь флаг REDUS_USE=True).
- Запускать в отдельном контейнере.
- Так же прописать в env.example необходимые секреты для этого

Пример реализации можно посмотреть в репозитории spread_wings. Улучшения приветсвуются)

# Where?

infra/
src/

**Comment by KonstantinRaikhert** [comment]
@Ezereul Надеюсь тебе понравится)) Дальше может быть еще интереснее с пакетами python-rq и django-rq

**Comment by KonstantinRaikhert** [comment]
@Ezereul Привет! Есть успехи?)

**Comment by Ezereul** [comment]
> @Ezereul Привет! Есть успехи?)

Привет, неожиданно закрутился на работе. Критично, если в пятницу будет готово?

**Comment by KonstantinRaikhert** [comment]
Не страшно!👌 Ждемс ПР тогда)
